# Generated by Django 6.0.2 on 2026-02-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIVoiceAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('airport', 'Airport'), ('medical', 'Medical')], max_length=20)),
                ('assistant_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('languages', models.CharField(max_length=200)),
                ('services', models.JSONField()),
                ('tone', models.CharField(max_length=50)),
                ('speaking_speed', models.CharField(max_length=50)),
                ('trigger_words', models.CharField(max_length=300)),
                ('escalate_after', models.IntegerField(default=1)),
                ('handoff_message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
